### ISSUE TITLE
Magento 2 OCA e-pak

### ISSUE THREAD

**Issue by jota-xx** [ombulabs/oca-epak#18]
Buenos dias, estoy empezando con magento 2.0 y queria saber si existe el modulo de OCA e-pak para esa version.
Desde ya muchas gracias

**Comment by etagwerker** [comment]
@jota-xx Esta es una gema (Ruby) que sirve para comunicarse con OCA e-pak. Magento 2.0 es todo PHP. Así que esta librería no te va a servir. 

Si querés usar esta gema, podrías probar haciendo un módulo para Spree o armando tu tienda online directamente con Rails.

**Comment by jota-xx** [comment]
OK, sigo buscando, el desarrollo que estoy armando ya esta hecho en magento 2.0, con mercado pago, pero quieren agregar OCA e-pak, pero aun no encontre nada, asi que tendre q empezar el modulo de cero.
Gracias

**Comment by mauro-oto** [comment]
@jota-xx podrias probar investigando esta otra libreria: https://github.com/juanchorossi/OCA-PHP-API/blob/master/oca.php.
